# Generated by Django 5.0.3 on 2026-05-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testa_app', '0003_merge_0002_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyactivity',
            options={'verbose_name': 'daily activity', 'verbose_name_plural': 'daily activities'},
        ),
        migrations.AlterModelOptions(
            name='exporthistory',
            options={'verbose_name': 'export history', 'verbose_name_plural': 'export history'},
        ),
    ]
